/*
 * Copyright 2021 - 2025 gnuwimp@gmail.com
 * Released under the GNU General Public License v3.0
 */

package gnuwimp.audiotageditor

/**
 * All sorts of genre tags.
 */
object Genre {
    val POPULAR = listOf(
        "Alternative",
        "Audiobook",
        "Black Metal",
        "Blues",
        "Classical",
        "Contemporary Classical",
        "Country",
        "Death Metal",
        "Electronic",
        "Folk",
        "Folk Rock",
        "Hard Rock",
        "Heavy Metal",
        "Hip-hop",
        "House",
        "Indie",
        "Jazz",
        "Metal",
        "Opera",
        "Pop",
        "Progressive Rock",
        "Psychedelic Rock",
        "Punk",
        "R&B",
        "Rap",
        "Reggae",
        "Rock",
        "Singer-songwriter",
        "Soul",
        "Techno",
        "World",
    )

    val ALTERNATIVE = listOf(
        "Alternative",
        "Acid Rock",
        "Alternative Rock",
        "Ambient",
        "Anime",
        "Audiobook",
        "Avant-garde",
        "Bitpop",
        "Cabaret",
        "Chiptune",
        "Comedy",
        "Crossover",
        "Easy Listening",
        "Electroacoustic",
        "Electronica",
        "Experimental",
        "Experimental Rock",
        "Indie",
        "Industrial",
        "Instrumental",
        "Lo-fi",
        "Meditative",
        "Musical Improvisation",
        "Nintendocore",
        "Progressive",
        "Psychedelic",
        "Psychedelic Rock",
        "Satire",
        "Sound Clip",
        "Soundtrack",
        "Speech",
        "Top 40",
        "Underground",
        "Video Game Music",
        "Vocal",
    )

    val BLUES = listOf(
        "Blues",
        "African Blues",
        "Blues Rock",
        "British Blues",
        "Chicago Blues",
        "Country Blues",
        "Delta Blues",
        "Desert Blues",
        "Detroit Blues",
        "Gospel Blues",
        "Jazz Blues",
        "New Orleans Blues",
        "St. Louis Blues",
        "Texas Blues",
        "West Coast Blues",
    )

    val CLASSICAL = listOf(
        "Classical",
        "A Cappella",
        "Baroque",
        "Chamber Opera",
        "Chamber",
        "Concert Aria",
        "Concerto",
        "Contemporary Classical",
        "Experimental",
        "High Modernism",
        "Impressionism",
        "Indian Classical",
        "March",
        "Medieval",
        "Minimalism",
        "Modernism",
        "Musical",
        "National Anthem",
        "Neoclassicism",
        "Nocturne",
        "Opera",
        "Oratorio",
        "Overture",
        "Persian Classical",
        "Prelude",
        "Quartet",
        "Quintet",
        "Renaissance",
        "Requiem",
        "Romantic",
        "Sinfonia Concertante",
        "Sinfonia",
        "Sonata",
        "Soundtrack",
        "Suite",
        "Symphony",
        "Toccata",
    )

    val COUNTRY = listOf(
        "Country",
        "Americana",
        "Bluegrass",
        "Cajun",
        "Country Blues",
        "Country Folk",
        "Country Pop",
        "Country Rap",
        "Country Rock",
        "Dansband",
        "Mexican Country",
        "Nashville",
        "Sothern Rock",
        "Trucker Country",
        "Western",
    )

    val ELECTRONIC = listOf(
        "Electronic",
        "Electronica",
        "Acid House",
        "Acid Techno",
        "Acid Trance",
        "Ambient House",
        "Ambient Techno",
        "Ambient",
        "Avant-garde",
        "Bass",
        "Chill-out",
        "D&B",
        "Disco",
        "Drum & Bass",
        "Dub",
        "EDM",
        "Electro House",
        "Electronic Rock",
        "Eurobeat",
        "Eurodance",
        "Eurodisco",
        "Experimental",
        "Goa Trance",
        "Hard Trance",
        "Hardcore",
        "Hip-hop",
        "House",
        "Krautrock",
        "New Wave",
        "New-age",
        "Post-rock",
        "Progressive Trance",
        "Psybient",
        "Psychedelic",
        "Psychedelic Trance",
        "Psydub",
        "Space Rock",
        "Spacemusic",
        "Techno",
        "Trance",
    )

    val FOLK = listOf(
        "Folk",
        "Americana",
        "British Folk Rock",
        "Cajun",
        "Celtic",
        "Chalga",
        "Contemporary Folk",
        "Creole",
        "Folk Rock",
        "Folk Pop",
        "Indie Folk",
        "Progressive Folk",
        "Protest Song",
        "Psychedelic Folk",
        "Singer-songwriter",
    )

    val HIPHOP = listOf(
        "Hip-hop",
        "African Hip-hop",
        "Bounce",
        "British Hip-hop",
        "Christian Hip-hop",
        "Cloud Rap",
        "Country Rap",
        "Gangsta Rap",
        "Latin Hip-hop",
        "Progressive Rap",
        "Rap",
        "UK Rap",
        "Underground Hip-hop",
    )

    val JAZZ = listOf(
        "Jazz",
        "Acid Jazz",
        "Afro-Cuban Jazz",
        "Avant-garde Jazz",
        "Bebop",
        "Big Band",
        "Bossa-nova",
        "Contemporary Jazz",
        "Dixieland",
        "Experimental Jazz",
        "Free Jazz",
        "Gypsy Jazz",
        "Hard Bop",
        "Jazz Blues",
        "Jazz Pop",
        "Jazz Rock",
        "Latin Jazz",
        "Progressive Jazz",
        "Ska Jazz",
        "Smooth Jazz",
        "Soul Jazz",
        "Swing",
        "Trad Jazz",
    )

    val METAL = listOf(
        "Metal",
        "Alternative Metal",
        "Avant-garde Metal",
        "Black Metal",
        "Brutal Black Metal",
        "Christian Metal",
        "Death Metal",
        "Death-doom",
        "Deathgrind",
        "Doom Metal",
        "Drone Metal",
        "Experimental Metal",
        "Extreme Metal",
        "Folk Metal",
        "Funeral Doom",
        "Funk Metal",
        "Gothic Doom",
        "Gothic Metal",
        "Hardcore",
        "Hardcore Punk",
        "Heavy Metal",
        "Industrial",
        "Industrial Metal",
        "Jazz Metal",
        "Melodic Death Metal",
        "Metalcore",
        "Post-metal",
        "Power Metal",
        "Progressive Death Metal",
        "Progressive Metal",
        "Speed Metal",
        "Stoner-doom",
        "Symphonic Black Metal",
        "Symphonic Metal",
        "Technical Death Metal",
        "Thrash Metal",
        "Viking Metal",
    )

    val POP = listOf(
        "Pop",
        "Alternative Pop",
        "Ambient Pop",
        "Art Pop",
        "Beach Pop",
        "Britpop",
        "C-pop",
        "Chanson",
        "Christian Pop",
        "Classic Hits",
        "Country Pop",
        "Dance-pop",
        "Electropop",
        "Emo Pop",
        "Eurobeat",
        "Europop",
        "Folk Pop",
        "French Pop",
        "Indie Pop",
        "J-pop",
        "Jazz Pop",
        "K-pop",
        "Latin Pop",
        "Nordic Pop",
        "Pop Rock",
        "Psychedelic Pop",
        "Schlager",
        "Surf Pop",
        "Synth-pop",
        "Worldbeat",
    )

    val RB = listOf(
        "R&B",
        "Alternative R&B",
        "Boogie",
        "Classic Soul",
        "Contemporary R&B",
        "Disco",
        "Doo-wop",
        "Funk",
        "Gospel",
        "Minneapolis Sound",
        "Northern Soul",
        "Psychedelic Funk",
        "Psychedelic Soul",
        "Sothern Gospel",
        "Sothern Soul",
        "Soul",
        "Synth-funk",
    )

    val ROCK = listOf(
        "Rock",
        "Acid Rock",
        "Afro Rock",
        "Alternative Rock",
        "American Rock",
        "Art Rock",
        "Blues Rock",
        "British Folk Rock",
        "Celtic Rock",
        "Christian Rock",
        "Desert Rock",
        "Electronic Rock",
        "Emo",
        "Experimental Rock",
        "Folk Rock",
        "Funk Rock",
        "Garage Punk",
        "Garage Rock",
        "Glam Rock",
        "Gothic Rock",
        "Hard Rock",
        "Hardcore",
        "Heavy Rock",
        "Indie",
        "Indie Rock",
        "Industrial",
        "Industrial Rock",
        "Japanese Rock",
        "Jazz Rock",
        "Krautrock",
        "New Wave",
        "Post-metal",
        "Post-punk",
        "Post-rock",
        "Progressive Rock",
        "Psychedelic Rock",
        "Punk",
        "Punk Rock",
        "Rock & Roll",
        "Rock Opera",
        "Rockabilly",
        "Roots Rock",
        "Southern Rock",
        "Space Rock",
        "Stoner Rock",
        "Symphonic Rock",
        "Viking Rock",
    )

    val WORLD = listOf(
        "World",
        "African",
        "African Hip-hop",
        "Afro House",
        "Afro Pop",
        "Afro Tech",
        "Afrobeat",
        "Anime",
        "Arabic Music",
        "Arabic Pop",
        "Asian",
        "Australasia",
        "Balkan Music",
        "Brazil Music",
        "C-pop",
        "Calypso",
        "Central Asian",
        "Chinese Folk Music",
        "Chinese Rock",
        "Dancehall",
        "Dub",
        "East Asian Music",
        "Ethnic",
        "Flamenco",
        "Hispanic",
        "J-pop",
        "Japanese Rock",
        "K-pop",
        "Latin Rock",
        "Klezmer",
        "Korean Music",
        "Korean Rock",
        "Merengue",
        "Middle Eastern Music",
        "Turkish Folk Music",
        "Māori Music",
        "Nordic",
        "Persian Traditional Music",
        "Raï",
        "Reggae",
        "Roots Reggae",
        "Rumba",
        "Salsa",
        "Ska",
        "South Asian",
        "Sufi Rock",
        "Taiwanese Pop",
        "Taiwanese Rock",
        "Tango",
        "Traditional Folk",
        "Tropical",
    )

    val GROUPS = listOf(
        "Popular",
        ALTERNATIVE[0],
        BLUES[0],
        CLASSICAL[0],
        COUNTRY[0],
        ELECTRONIC[0],
        FOLK[0],
        HIPHOP[0],
        JAZZ[0],
        METAL[0],
        POP[0],
        RB[0],
        ROCK[0],
        WORLD[0],
    )

    /**
     * Return list of group names for genres.
     */
    fun get(name: String): List<String> {
        println(name)
        return when (name) {
            "Popular" -> POPULAR
            ALTERNATIVE[0] -> ALTERNATIVE
            BLUES[0] -> BLUES
            CLASSICAL[0] -> CLASSICAL
            COUNTRY[0] -> COUNTRY
            ELECTRONIC[0] -> ELECTRONIC
            FOLK[0] -> FOLK
            HIPHOP[0] -> HIPHOP
            JAZZ[0] -> JAZZ
            METAL[0] -> METAL
            POP[0] -> POP
            RB[0] -> RB
            ROCK[0] -> ROCK
            WORLD[0] -> WORLD
            else -> POPULAR
        }
    }
}
